events {}

http {
    map $arg_url $titiler_hash_key {
        default $arg_url;
        "" $request_uri;
    }

    upstream titiler_backends {
        hash $titiler_hash_key consistent;

        server titiler-1:8000;
        server titiler-2:8000;
        server titiler-3:8000;
        server titiler-4:8000;
    }

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        ssl_certificate /etc/nginx/ssl/strayos.com.crt;
        ssl_certificate_key /etc/nginx/ssl/star_strayos_com.key;

        location / {
            proxy_pass http://titiler_backends;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
